kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: normal-server
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: safe
  volumeMode: Filesystem
