{{- range .Values.servers}}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}
  namespace: uff-mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      volumes:
        - name: {{.name}}
          persistentVolumeClaim:
            claimName: {{.name}}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mc
          env:
            - name: EULA
              value: 'TRUE'
            - name: ICON
              value: https://avatars.githubusercontent.com/u/108249294?s=64&v4
            {{- if .env}}
            {{- range .env}}
            - name: {{ .name }}
              value: {{ quote .value }}
            {{- end}}
            {{- end}}
          ports:
            - containerPort: 25565
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: {{.name}}
              mountPath: /data
          terminationMessagePolicy: File
          image: 'itzg/minecraft-server:java8-graalvm-ce'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.name}}
  namespace: uff-mc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.storage }}
  storageClassName: safe
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: {{.name}}
  annotations:
    "mc-router.itzg.me/externalServerName": "{{.name}}.apps.kuwu.uff.cool"
spec:
  ports:
    - port: 25565
  selector:
    name: {{.name}}
  {{- end}}